### ISSUE TITLE
recur yields syntax error

### ISSUE THREAD

**Issue by chr15m** [yardsale8/hymagic#2]
Hi, I reported #1 and I've found another small bug. The following works in `hy` called from the command line:

```
$ hy
hy 0.11.1 using CPython(default) 2.7.6 on Linux
=> (import [random [random randint choice]])
=> (require hy.contrib.loop)
=> (def note-jump-probabilities [5 5 5 5 5 7 7 7 3 3 3 6 6 2 2 4 4 1])
=> (defn get-good-notes [n]
...   (loop [[c (dec n)] [notes [(randint 0 12)]]]
...     (if (> c 0)
...       (recur (dec c) (+ notes [(% (+ (get notes -1) (choice note-jump-probabilities)) 12)]))
...       (sorted notes))))
=> (get-good-notes 8)
[0L, 2L, 5L, 5L, 6L, 7, 10L, 11L]
```

But the same thing in a notebook fails:

```
In [8]:

(def note-jump-probabilities [5 5 5 5 5 7 7 7 3 3 3 6 6 2 2 4 4 1])
(defn get-good-notes [n]
  (loop [[c (dec n)] [notes [(randint 0 12)]]]
    (if (> c 0)
      (recur (dec c) (+ notes [(% (+ (get notes -1) (choice note-jump-probabilities)) 12)]))
      (sorted notes))))
  File "<ipython-input-8-c9c959b11203>", line 8
    def :recur_fn_1240(c, notes):
        ^
SyntaxError: invalid syntax
```

**Comment by yardsale8** [comment]
Sorry for the last response.  I am having trouble reproducing your issues.  Here is the above code executing in the ipython console:

```
In [1]: %load_ext hymagic

In [2]: %%hylang
(import [random [random randint choice]])
(require hy.contrib.loop)
(def note-jump-probabilities [5 5 5 5 5 7 7 7 3 3 3 6 6 2 2 4 4 1])
(def note-jump-probabilities [5 5 5 5 5 7 7 7 3 3 3 6 6 2 2 4 4 1])
(defn get-good-notes [n]
  (loop [[c (dec n)] [notes [(randint 0 12)]]]
    (if (> c 0)
      (recur (dec c) (+ notes [(% (+ (get notes -1) (choice note-jump-probabilities)) 12)]))
      (sorted notes))))
(get-good-notes 8)
   ...:
Out[2]: [1, 4L, 6L, 6L, 7L, 9L, 10L, 11L]
```

This also seems to be working in the ipython notebook.  **Note the first line of the cell is `%%hylang`**  This cell magic needs to be alone on the first line of the cell, both in the console and in a notebook cell.  

Since each of your examples is missing the cell magic, I think your might be using the completion branch, which makes an attempt to execute python and hylang together without the need for magic invocations.  Unfortunately, it is pretty experimental.  I might be able to come back to this branch later this summer...

Are you able to get the code to complete using the hylang cell magic as shown above?

**Comment by chr15m** [comment]
@yardsale8 ok I've figured out what's going on here, and with #1.

You're right that running from iPython console and iPython Notebook (in Python mode) the above works fine.

What I was doing was in Jupyter (iPython Notebook) going to the 'New' pulldown menu and selecting 'Hy'. This creates a new notebook which evidently runs the `%load_ext hymagic` and `%%hylang` magics implicitly. This is great because you can just write Hy code without worrying but unfortunately it seems it doesn't interact well with the plugin you have written. If I get some time I'll try and diagnose why not but in the short term I guess I'll resort to typing the `%%hylang` magic in each block.

Thanks for your help!
